# Generated by Django 5.1.1 on 2024-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagamfoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
