# Generated by Django 5.1.1 on 2024-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0002_mfm'),
    ]

    operations = [
        migrations.CreateModel(
            name='KFM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('model', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
