# Generated by Django 5.1.1 on 2024-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0003_kfm'),
    ]

    operations = [
        migrations.AddField(
            model_name='kfm',
            name='Available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mfm',
            name='Available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wfm',
            name='Available',
            field=models.IntegerField(default=0),
        ),
    ]
