# Generated by Django 5.1.1 on 2024-10-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0004_kfm_available_mfm_available_wfm_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='kfm',
            name='articleno',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='mfm',
            name='articleno',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wfm',
            name='articleno',
            field=models.IntegerField(default=2),
        ),
    ]
