# Generated by Django 5.1.1 on 2024-10-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0005_kfm_articleno_mfm_articleno_wfm_articleno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('product', models.CharField(max_length=255)),
            ],
        ),
    ]
