# Generated by Django 5.1.1 on 2024-10-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0006_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kfm',
            name='articleno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mfm',
            name='articleno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wfm',
            name='articleno',
            field=models.CharField(max_length=100),
        ),
    ]
