# Generated by Django 5.1.1 on 2024-10-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0007_alter_kfm_articleno_alter_mfm_articleno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kfm',
            name='Available',
        ),
        migrations.RemoveField(
            model_name='mfm',
            name='Available',
        ),
        migrations.RemoveField(
            model_name='wfm',
            name='Available',
        ),
        migrations.CreateModel(
            name='KFMSizeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='categoryc.kfm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFMSizeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='categoryc.mfm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WFMSizeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='categoryc.wfm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
