# Generated by Django 5.1.1 on 2024-10-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0009_purchase_created_at_alter_purchase_landmark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kfm',
            options={'verbose_name': "Kids' Footwear", 'verbose_name_plural': "Kids' Footwear"},
        ),
        migrations.AlterModelOptions(
            name='kfmsizeavailability',
            options={'verbose_name': "Kids' Footwear Size", 'verbose_name_plural': "Kids' Footwear Sizes"},
        ),
        migrations.AlterModelOptions(
            name='mfm',
            options={'verbose_name': "Men's Footwear", 'verbose_name_plural': "Men's Footwear"},
        ),
        migrations.AlterModelOptions(
            name='mfmsizeavailability',
            options={'verbose_name': "Men's Footwear Size", 'verbose_name_plural': "Men's Footwear Sizes"},
        ),
        migrations.AlterModelOptions(
            name='wfm',
            options={'verbose_name': "Women's Footwear", 'verbose_name_plural': "Women's Footwear"},
        ),
        migrations.AlterModelOptions(
            name='wfmsizeavailability',
            options={'verbose_name': "Women's Footwear Size", 'verbose_name_plural': "Women's Footwear Sizes"},
        ),
    ]
