# Generated by Django 5.1.1 on 2024-10-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0012_alter_purchase_user_bagitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='size',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
