# Generated by Django 5.2.4 on 2026-04-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0014_order_models_and_bag_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='kfm',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kfm',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='kfm',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mfm',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mfm',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='mfm',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wfm',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wfm',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='wfm',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
