# Generated by Django 5.2.12 on 2026-04-05 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryc', '0015_kfm_mrp_kfm_rating_kfm_rating_count_mfm_mrp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order', 'Order'), ('promotion', 'Promotion'), ('account', 'Account'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='categoryc.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='categoryc_n_user_id_46d7dd_idx'), models.Index(fields=['user', 'read_at'], name='categoryc_n_user_id_457eb4_idx')],
            },
        ),
    ]
