"""
Django settings for the e-commerce project (config package).

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import re

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(
    os.environ.get('DJANGO_DEBUG', os.environ.get('DEBUG', 'False'))
).lower() in ('1', 'true', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (os.environ.get('DJANGO_SECRET_KEY') or os.environ.get('SECRET_KEY') or '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-nn$rj5w-v^r*#!3!e5+on^l8r4=yurirhid1ummc%4#qb3d9mf'
    else:
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY (or SECRET_KEY) when DEBUG is False.')

# Comma-separated hostnames, e.g. "app.onrender.com,example.com"
_raw_allowed = (os.environ.get('DJANGO_ALLOWED_HOSTS') or os.environ.get('ALLOWED_HOSTS') or '').strip()
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
elif not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'Set DJANGO_ALLOWED_HOSTS (or ALLOWED_HOSTS) to a comma-separated list of hostnames.'
    )

LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# django-allauth (Google OAuth). Site + auth backends required.
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Application definition

INSTALLED_APPS = [
    'store.apps.StoreConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'cloudinary',
    'cloudinary_storage',
    'accounts',
    'categories.apps.CategoriesConfig',
    'adminpanel.apps.AdminpanelConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'categories.context_processors.bag_summary',
                'categories.context_processors.notification_preview',
                'categories.context_processors.push_bootstrap',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


def _database_from_env() -> dict:
    """Prefer DATABASE_URL; else Postgres via PG* / POSTGRES_* (e.g. Neon, Render)."""
    url = (os.environ.get('DATABASE_URL') or '').strip()
    if url:
        return {
            'default': dj_database_url.parse(
                url,
                conn_max_age=600,
                ssl_require=True,
            )
        }
    name = (os.environ.get('PGDATABASE') or os.environ.get('POSTGRES_DB') or '').strip()
    user = (os.environ.get('PGUSER') or os.environ.get('POSTGRES_USER') or '').strip()
    password = (os.environ.get('PGPASSWORD') or os.environ.get('POSTGRES_PASSWORD') or '').strip()
    host = (os.environ.get('PGHOST') or os.environ.get('POSTGRES_HOST') or '').strip()
    port = (os.environ.get('PGPORT') or os.environ.get('POSTGRES_PORT') or '5432').strip()
    if name and user and password and host:
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': name,
                'USER': user,
                'PASSWORD': password,
                'HOST': host,
                'PORT': port,
                'OPTIONS': {'sslmode': 'require'},
            }
        }
    raise ImproperlyConfigured(
        'Set DATABASE_URL, or PGDATABASE, PGUSER, PGPASSWORD, PGHOST '
        '(and optionally PGPORT).'
    )


DATABASES = _database_from_env()
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Local dev uses HTTP; Secure cookies break sessions + OAuth callback unless HTTPS.
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG

# --- django-allauth account / social (Google) ---
ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
# Skip the plain allauth "Sign in via Google" confirmation page; go straight to Google OAuth.
SOCIALACCOUNT_LOGIN_ON_GET = True

_GOOGLE_OAUTH_CLIENT_ID = (os.environ.get('GOOGLE_OAUTH_CLIENT_ID') or '').strip()
_GOOGLE_OAUTH_CLIENT_SECRET = (os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET') or '').strip()

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}
if _GOOGLE_OAUTH_CLIENT_ID and _GOOGLE_OAUTH_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS['google']['APP'] = {
        'client_id': _GOOGLE_OAUTH_CLIENT_ID,
        'secret': _GOOGLE_OAUTH_CLIENT_SECRET,
        'key': '',
    }

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if not DEBUG else 'http'
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Leading slash so {% static %} URLs are root-absolute (works on every path; required for WhiteNoise).
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR / "static")  
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


def _parse_cloudinary_url(url: str) -> dict[str, str]:
    """
    Parse cloudinary://API_KEY:API_SECRET@CLOUD_NAME
    (same format as the Cloudinary dashboard env template).
    """
    url = (url or '').strip()
    if not url.startswith('cloudinary://'):
        return {}
    rest = url[len('cloudinary://') :]
    if '@' not in rest:
        return {}
    creds, cloud = rest.rsplit('@', 1)
    if ':' not in creds:
        return {}
    key, secret = creds.split(':', 1)
    return {
        'CLOUD_NAME': cloud.strip(),
        'API_KEY': key.strip(),
        'API_SECRET': secret.strip(),
    }


_cloudinary_from_url = _parse_cloudinary_url(os.environ.get('CLOUDINARY_URL', ''))

# Cloudinary (uploaded media). Prefer CLOUDINARY_URL in .env, or the three vars — do not commit secrets.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _cloudinary_from_url.get('CLOUD_NAME')
    or (os.environ.get('CLOUDINARY_CLOUD_NAME') or '').strip(),
    'API_KEY': _cloudinary_from_url.get('API_KEY')
    or (os.environ.get('CLOUDINARY_API_KEY') or '').strip(),
    'API_SECRET': _cloudinary_from_url.get('API_SECRET')
    or (os.environ.get('CLOUDINARY_API_SECRET') or '').strip(),
}


def _cloudinary_cloud_name_looks_valid(name: str) -> bool:
    """
    Values like "Footwear" are folder/brand labels, not Cloudinary cloud_name.
    Wrong names still pass non-empty checks and break uploads at API time.
    Real names come from the Cloudinary dashboard (lowercase, letters, digits, hyphens).
    """
    if len(name) < 3:
        return False
    return bool(re.fullmatch(r'[a-z0-9][a-z0-9_-]*', name))


_cloudinary_ready = (
    all(CLOUDINARY_STORAGE[k] for k in ('CLOUD_NAME', 'API_KEY', 'API_SECRET'))
    and _cloudinary_cloud_name_looks_valid(CLOUDINARY_STORAGE['CLOUD_NAME'])
)
# Production (e.g. Render): WhiteNoise serves collected static files from STATIC_ROOT.
_staticfiles_backend = (
    'whitenoise.storage.CompressedStaticFilesStorage'
    if not DEBUG
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)
if _cloudinary_ready:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': _staticfiles_backend,
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': _staticfiles_backend,
        },
    }


def _env_bool(name: str, default: bool) -> bool:
    raw = (os.environ.get(name) or '').strip().lower()
    if not raw:
        return default
    return raw in ('1', 'true', 'yes', 'on')


# Public site URL for absolute links in emails and push payloads (no trailing slash).
SITE_PUBLIC_URL = (os.environ.get('SITE_PUBLIC_URL') or '').strip().rstrip('/')

# --- Outbound notifications (email / SMS / web push) ---
# Each created Notification row can trigger these channels; see categories/messaging.py.
NOTIFICATION_EMAIL = _env_bool('NOTIFICATION_EMAIL', True)
NOTIFICATION_SMS = _env_bool('NOTIFICATION_SMS', False)
NOTIFICATION_WEB_PUSH = _env_bool('NOTIFICATION_WEB_PUSH', True)

_default_email_backend = (
    'django.core.mail.backends.console.EmailBackend'
    if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_BACKEND = (os.environ.get('EMAIL_BACKEND') or _default_email_backend).strip()
EMAIL_HOST = (os.environ.get('EMAIL_HOST') or '').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587') or '587')
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = (os.environ.get('EMAIL_HOST_USER') or '').strip()
EMAIL_HOST_PASSWORD = (os.environ.get('EMAIL_HOST_PASSWORD') or '').strip()
DEFAULT_FROM_EMAIL = (os.environ.get('DEFAULT_FROM_EMAIL') or 'noreply@localhost').strip()
SERVER_EMAIL = DEFAULT_FROM_EMAIL

TWILIO_ACCOUNT_SID = (os.environ.get('TWILIO_ACCOUNT_SID') or '').strip()
TWILIO_AUTH_TOKEN = (os.environ.get('TWILIO_AUTH_TOKEN') or '').strip()
TWILIO_FROM_NUMBER = (os.environ.get('TWILIO_FROM_NUMBER') or '').strip()

VAPID_PUBLIC_KEY = (os.environ.get('VAPID_PUBLIC_KEY') or '').strip()
_vapid_pk_raw = (os.environ.get('VAPID_PRIVATE_KEY') or '').strip()
VAPID_PRIVATE_KEY = _vapid_pk_raw.replace('\\n', '\n') if _vapid_pk_raw else ''
VAPID_ADMIN_EMAIL = (os.environ.get('VAPID_ADMIN_EMAIL') or 'mailto:admin@localhost').strip()
if not VAPID_ADMIN_EMAIL.startswith(('mailto:', 'https://', 'http://')):
    VAPID_ADMIN_EMAIL = f'mailto:{VAPID_ADMIN_EMAIL}'