"""
Django settings for the e-commerce project (config package).

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import re

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nn$rj5w-v^r*#!3!e5+on^l8r4=yurirhid1ummc%4#qb3d9mf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# django-allauth (Google OAuth). Site + auth backends required.
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Application definition

INSTALLED_APPS = [
    'store.apps.StoreConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'cloudinary',
    'cloudinary_storage',
    'accounts',
    'categories.apps.CategoriesConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'categories.context_processors.bag_summary',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'neondb',  # your DB name
        'USER': 'neondb_owner',
        'PASSWORD': 'npg_bHwJCK0FZk3N',
        'HOST': 'ep-tiny-snow-amc725bi-pooler.c-5.us-east-1.aws.neon.tech',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require'
        }
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Local dev uses HTTP; Secure cookies break sessions + OAuth callback unless HTTPS.
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True

# --- django-allauth account / social (Google) ---
ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
# Skip the plain allauth "Sign in via Google" confirmation page; go straight to Google OAuth.
SOCIALACCOUNT_LOGIN_ON_GET = True

_GOOGLE_OAUTH_CLIENT_ID = (os.environ.get('GOOGLE_OAUTH_CLIENT_ID') or '').strip()
_GOOGLE_OAUTH_CLIENT_SECRET = (os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET') or '').strip()

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}
if _GOOGLE_OAUTH_CLIENT_ID and _GOOGLE_OAUTH_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS['google']['APP'] = {
        'client_id': _GOOGLE_OAUTH_CLIENT_ID,
        'secret': _GOOGLE_OAUTH_CLIENT_SECRET,
        'key': '',
    }

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if not DEBUG else 'http'
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR / "static")  
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


def _parse_cloudinary_url(url: str) -> dict[str, str]:
    """
    Parse cloudinary://API_KEY:API_SECRET@CLOUD_NAME
    (same format as the Cloudinary dashboard env template).
    """
    url = (url or '').strip()
    if not url.startswith('cloudinary://'):
        return {}
    rest = url[len('cloudinary://') :]
    if '@' not in rest:
        return {}
    creds, cloud = rest.rsplit('@', 1)
    if ':' not in creds:
        return {}
    key, secret = creds.split(':', 1)
    return {
        'CLOUD_NAME': cloud.strip(),
        'API_KEY': key.strip(),
        'API_SECRET': secret.strip(),
    }


_cloudinary_from_url = _parse_cloudinary_url(os.environ.get('CLOUDINARY_URL', ''))

# Cloudinary (uploaded media). Prefer CLOUDINARY_URL in .env, or the three vars — do not commit secrets.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _cloudinary_from_url.get('CLOUD_NAME')
    or (os.environ.get('CLOUDINARY_CLOUD_NAME') or '').strip(),
    'API_KEY': _cloudinary_from_url.get('API_KEY')
    or (os.environ.get('CLOUDINARY_API_KEY') or '').strip(),
    'API_SECRET': _cloudinary_from_url.get('API_SECRET')
    or (os.environ.get('CLOUDINARY_API_SECRET') or '').strip(),
}


def _cloudinary_cloud_name_looks_valid(name: str) -> bool:
    """
    Values like "Footwear" are folder/brand labels, not Cloudinary cloud_name.
    Wrong names still pass non-empty checks and break uploads at API time.
    Real names come from the Cloudinary dashboard (lowercase, letters, digits, hyphens).
    """
    if len(name) < 3:
        return False
    return bool(re.fullmatch(r'[a-z0-9][a-z0-9_-]*', name))


_cloudinary_ready = (
    all(CLOUDINARY_STORAGE[k] for k in ('CLOUD_NAME', 'API_KEY', 'API_SECRET'))
    and _cloudinary_cloud_name_looks_valid(CLOUDINARY_STORAGE['CLOUD_NAME'])
)
if _cloudinary_ready:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }